# See https://docs.docker.com/compose/compose-file/

version: "3"
services:
  docket-vault:
    container_name: docket-vault
    # build: ./docker/vault
    image: docket-api_docket-vault
    ports:
      - 8200:8200
  docket-swagger-ui:
    container_name: docket-swagger-ui
    image: swaggerapi/swagger-ui
    ports:
      - 3200:8080
  docket-redis:
    container_name: docket-redis
    # build: ./docker/redis
    image: docket-api_docket-redis
    ports:
      - 6379:6379
  docket-postgres:
    container_name: docket-postgres
    # build: ./docker/postgres
    image: docket-api_docket-postgres
    ports:
      - 5432:5432
    # environment:
    #   POSTGRES_USER: 'user'
    #   POSTGRES_PASSWORD: 'user'
  docket-elasticsearch:
    container_name: docket-elasticsearch
    # image: elasticsearch:7.2.0
    # build: ./docker/elasticsearch
    image: docket-api_docket-elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    # networks:
    #   - docket
    environment:
      - discovery.type=single-node
    # healthcheck:
    #   test: docker-healthcheck-elasticsearch
    #   interval: 60s
    #   timeout: 10s
    #   retries: 3
  docket-kibana:
    container_name: docket-kibana
    image: kibana:7.2.0
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: 'http://docket-elasticsearch:9200'
    depends_on:
      - docket-elasticsearch
        # condition: service_healthy
    # links:
    #   - docket-elasticsearch
    # networks:
    #   - docket
  # docket-mongo:
  #   container_name: docket-mongo
  #   image: mongo:4.0.3
  #   ports:
  #     - '27017:27017'
  #   # volumes:
  #   #   - ./data/db:/data/db
  #   # environment:
  #   #   MONGO_INITDB_ROOT_USERNAME: ''
  #   #   MONGO_INITDB_ROOT_PASSWORD: 'root'
  docket-api:
    entrypoint: ["./docker-entrypoint.sh"]
    container_name: docket-api
    image: docket-api_docket-api
    # build: .
    # command: npm run start
    # working_dir: /docket/docket-api
    # volumes:
    #   - .:/docket/docket-api
    ports:
      - 3001:3001
      # - 9222:9222
      # - 9229:9229
      - 9299:9299
    depends_on:
      - docket-postgres
        # condition: service_healthy
      - docket-redis
        # condition: service_healthy
      - docket-elasticsearch
        # condition: service_healthy
      - docket-vault
        # condition: service_healthy
    # links:
    #   - docket-postgres
    #   - docket-redis
    #   - docket-elasticsearch
  docket-worker:
    # entrypoint: ["./docker-entrypoint.sh"]
    container_name: docket-worker
    # build: .
    image: docket-api_docket-worker
    # command: node --inspect=0.0.0.0 ./index.js
    # command: npm run start:worker
    # working_dir: /docket/docket-worker
    # volumes:
    #   - .:/docket/docket-worker
    # ports:
      # - '3000:3000'
      # - '9222:9222'
      # - '9229:9229'
      # - '9299:9299'
    depends_on:
      # - docket-postgres
      - docket-redis
        # condition: service_healthy
      - docket-elasticsearch
        # condition: service_healthy
      - docket-vault
        # condition: service_healthy
      # docket-api:
      #   condition: service_healthy
      # docket-postgres:
      #   condition: service_healthy
    # links:
    #   # - docket-postgres
    #   - docket-redis
    #   - docket-elasticsearch
