FROM vault:1.3.0
RUN apk add curl
# COPY docker-healthcheck-vault /usr/local/bin/

# A free-to-use tool that scans container images for package vulnerabilities.
# See https://github.com/aquasecurity/microscanner
# ADD https://get.aquasec.com/microscanner /
# RUN chmod +x /microscanner
# RUN /microscanner N2JlNzQzY2VmNmM1

# HEALTHCHECK CMD docker-healthcheck-vault
