version: 2
jobs:
  lint:
    working_directory: ~/docket/docket-api
    docker:
      - image: circleci/node:12.10.0
    steps:
      - checkout
      - run:
          name: Update NPM
          command: sudo npm i -g npm@latest
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install NPM packages
          command: npm ci
      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Lint
          command: npm run lint
  test:
    working_directory: ~/docket/docket-api
    docker:
      - image: circleci/node:12.10.0
    steps:
      - checkout
      - run:
          name: Update NPM
          command: sudo npm i -g npm@latest
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install NPM packages
          command: npm ci
      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Run unit tests
          command: npm run test:unit
      - run:
          name: Upload test results to Coveralls
          command: cat ./coverage/lcov.info | $(npm bin)/coveralls
      - store_artifacts:
          path: test-results
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: test-results
workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - test
