version: 2
jobs:
  build:
    working_directory: ~/docket/docket-api
    docker:
      - image: circleci/node:12.10.0
    steps:
      - checkout
      - run:
          name: npm-update
          command: sudo npm i -g npm@latest
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: npm-install
          command: npm ci
      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test-unit
          command: npm run test:unit
      - run:
          name: test-coveralls
          command: cat ./coverage/lcov.info | $(npm bin)/coveralls
      - store_artifacts:
          path: ./junit.xml
          destination: test
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_test_results:
          path: ./junit.xml
workflows:
  version: 2
  build:
    jobs:
      - build
