AWSTemplateFormatVersion: "2010-09-09"
Description: Docket API secrets
Parameters:
  EnvironmentNameParameter:
    AllowedPattern: "^[a-z]+$"
    AllowedValues:
      - "staging"
      - "production"
    Description: "The environment in which the application will run"
    Type: "String"
  VaultAppRoleIdParameter:
    Description: "Vault AppRole ID"
    NoEcho: true
    Type: "String"
  VaultAppRoleSecretWrapTokenParameter:
    Description: "Vault AppRole secret wrap token"
    NoEcho: true
    Type: "String"
Resources:
  VaultAppRoleIdSSMParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Join ["-", ["vault-app-role-id", !Ref "EnvironmentNameParameter"]]
      Tier: "Standard"
      Type: "String"
      Value: !Ref "VaultAppRoleIdParameter"
  VaultAppRoleSecretWrapTokenSSMParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Join ["-", ["vault-app-role-secret-wrap-token", !Ref "EnvironmentNameParameter"]]
      Tier: "Standard"
      Type: "String"
      Value: !Ref "VaultAppRoleSecretWrapTokenParameter"
